import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electron', {
  getLocalStoragePath: () => ipcRenderer.invoke('get-local-storage-path'),
  chooseDataFolder: () => ipcRenderer.invoke('choose-data-folder'),
  getPrinters: () => ipcRenderer.invoke('get-printers'),
  getPrinterSettings: () => ipcRenderer.invoke('get-printer-settings'),
  setPrinterSettings: (payload: { printerSmall?: string; printerBig?: string }) => ipcRenderer.invoke('set-printer-settings', payload),
  getProducts: () => ipcRenderer.invoke('get-products'),
  saveProducts: (products: unknown[]) => ipcRenderer.invoke('save-products', products),
  addProduct: (product: unknown) => ipcRenderer.invoke('add-product', product),
  deleteProduct: (id: string) => ipcRenderer.invoke('delete-product', id),
  getGroups: () => ipcRenderer.invoke('get-groups'),
  saveGroups: (groups: unknown[]) => ipcRenderer.invoke('save-groups', groups),
  addGroup: (group: unknown) => ipcRenderer.invoke('add-group', group),
  deleteGroup: (id: string) => ipcRenderer.invoke('delete-group', id),
  getRecipes: () => ipcRenderer.invoke('get-recipes'),
  saveRecipes: (recipes: unknown[]) => ipcRenderer.invoke('save-recipes', recipes),
  addRecipe: (recipe: unknown) => ipcRenderer.invoke('add-recipe', recipe),
  getCompanies: () => ipcRenderer.invoke('get-companies'),
  addCompany: (company: unknown) => ipcRenderer.invoke('add-company', company),
  getMachineId: () => ipcRenderer.invoke('get-machine-id'),
  licenseGetState: () => ipcRenderer.invoke('license-get-state'),
  licenseSetLicensed: () => ipcRenderer.invoke('license-set-licensed'),
  licenseSetTrialEndsAt: (trialEndsAt: string) => ipcRenderer.invoke('license-set-trial-ends-at', trialEndsAt),
  licenseStartTrial: (machineId: string) => ipcRenderer.invoke('license-start-trial', machineId),
  licenseCheckTrial: (machineId: string) => ipcRenderer.invoke('license-check-trial', machineId),
  licenseActivate: (key: string, machineId: string) => ipcRenderer.invoke('license-activate', key, machineId),
  licenseCheck: (machineId: string) => ipcRenderer.invoke('license-check', machineId),
})
